# Site settings
title: Unexpected Inventions
tag_text: Unexpected Inventions
description: Welcome to the unexpected
url: "https://www.unexpectedinventions.com/" 
baseurl: "" 
font-awesome-include: true 

# Build settings
markdown: kramdown

exclude: ["README.md"]

permalink: /:title/

